<?php

$globalUrl = 'http://localhost:8080';

$errors = [
    'csrf' => 'Votre session est invalide.',
    'referer' => 'D\'où venez vous ?',
    'name_host' => 'Saisissez un nom',
    'name_category' => 'Saisissez un nom de catégorie',
    'name_subCategory' => 'Saisissez un nom de sous catégorie',
    'error_check' => 'l erreure est ici',
    'add-subCategory_ko' => 'Sous-catégorie non ajoutée',
    'add-category_ko' => 'Categorie non ajoutée',
    'host' => 'Sélectionnez un intervenant',
    'category' => 'Sélectionnez une catégorie',
    'sub_category' => 'Sélectionnez une sous-catégorie',
    'date' => 'Saisissez une date',
    'add-formation_ko' => 'Formation non ajoutée',
    'edit-formation_ko' => 'Formation non modifiée',
    'connexion_nameAdmin' => 'Erreur connexion',
    'connexion_nameAdmin_size' => 'Erreur connexion',
    'connexion_password' => 'Erreur connexion',
    'connexion_password_size' => 'Erreur connexion',
    'error_connexion' => 'Erreur connexion',
    'create_nameAdmin' => 'Saisissez un nom',
    'nameAdmin_size' => 'Saisissez un nom de 50 caractères maximum',
    'password' => 'Saisissez un mot de passe',
    'create-admin_ok' => 'Admin enregistré',
    'create-admin_ko' => 'Admin non enregistré',
    'edit-subCategory_ko' => 'Sous-catégorie non renseignée',
    'edit-category_ko' => 'Categorie non renseignée',
    'edit-host_ko' => 'Intervenant non renseigné',
    'price' =>  'Saisissez un prix, si pas de prix saisissez 0',
    'nb_participants' => 'Saisissez un nombre de participants, si pas de participants saisissez 0',
    'edit-participants_ko' => 'Nombre de participants non renseigné',
    'lastname_null' => 'Saisissez un nom',
    'lastname_size' => 'Saisissez un nom de 50 caractères maximum',
    'firstname_null' => 'Saisissez un prénom',
    'firstname_size' => 'Saisissez un prénom de 50 caractères maximum',
    'email_null' => 'Saisissez un email',
    'echec_inscription' => 'Échec inscription',
];

$messages = [
    'add_product_ok' => 'Produit enregistré',
    'add-subCategory_ok' => 'Sous-catégorie ajoutée',
    'add-category_ok' => 'Categorie ajoutée',
    'add-intervenant_ok' => 'Intervenant ajouté',
    'add-formation_ok' => 'Formation ajoutée',
    'edit-formation_ok' => 'Formation modifiée',
];